<div class="banner">
<a href="http://www.youtube.com/watch?v=YTFKhTRmNIs&list=UUezJIH5Fw6BKox_urjUB7Gw&index=1&feature=plcp" target="_blank"><img src="/img/common/banner_yamatogokoro.jpg" alt="イやまとごころTV" /></a>
</div>

<div class="banner">
<a href="http://www.k-tsushin.jp/inbound/search/details/008238/" target="_blank"><img src="/img/common/inbound30.gif" alt="インバウンド観光支援のプロフェッショナル30" /></a>
</div>

<div class="banner">
<a href="http://www.k-tsushin.jp/china100/search/details/000934/" target="_blank"><img src="/img/common/china100.gif" alt="中国100選" /></a>
</div>

<div class="banner">
<a href="http://www.chinabusiness-headline.com/author/yahagi/" target="_blank"><img src="/img/common/banner_headline.jpg" alt="中国ビジネスヘッドライン" /></a>
</div>

<div class="banner">
<a href="http://markezine.jp/article/corner/392" target="_blank"><img src="/img/common/banner_markezine.jpg" alt="中国Webマーケティング最前線" /></a>
</div>



<div class="banner">
<a href="/partner/"><img src="/img/common/banner_partner_off.jpg" alt="セールスパートナーのお問い合わせ" /></a>
</div>

<div class="banner">
<a href="http://www.813.co.jp/blog/index/owner/yahagi" target="_blank"><img src="/img/common/blog_banner_y_off.jpg" alt="81代表ブログ" /></a>
<a href="http://www.813.co.jp/blog/index/owner/sakaguchi" target="_blank"><img src="/img/common/blog_banner_s_off.jpg" alt="中国マーケティングプランナーの奮闘記" /></a>
<a href="http://www.813.co.jp/recruit/" target="_blank"><img src="/img/common/recruit_banner.jpg" alt="81採用情報" /></a>
</div>

<div class="banner">
<a href="/tool/input"><img src="/img/common/banner_tool_off.jpg" alt="中国向けWEBサイトパフォーマンスツール" /></a>
</div>