<div id="footer">
<div id="footer-inner">
<div id="f-navi" class="clearfix">
<ul>
<li><a href="/">ホーム</a></li>
{*<li class="seo"><a href="/seo">百度（baidu）SEOサービス</a></li>*}
<li class="weibo"><a href="/weibo">ウェイボー（微博）運用代行サービス</a></li>
<li class="pr"><a href="/pr">中国4大ポータル記事掲載保証PR</a></li>
{*<li class="sem"><a href="/sem">百度（baidu）SEMサービス</a></li>*}
<li class="rapid"><a href="/rapid">中国サイト快速サービス</a></li>
<li class="kujapan"><a href="/kujapan">日遊酷棒（リーヨウクーバン）</a></li>
<li class="bbs"><a href="/bbs">中国BBS口コミPR</a></li>
<li class="microblog"><a href="/microblog">中国マイクロブログ（微博）PR</a></li>
<li class="blogger"><a href="/blogger">中国人気ブロガーPR</a></li>
<li class="baike"><a href="/baike">百度百科登録</a></li>
<li class="zhidao"><a href="/zhidao">百度知道登録</a></li>
<li><a href="/tool/input">中国向けWEBサイトパフォーマンスツール</a></li>
<li><a href="/inquiry/input">お問い合わせ</a></li>
<li><a href="/partner/inquiry/input">セールスパートナーお問い合わせ</a></li>
<li><a href="/corp">運営</a></li>
</ul>
</div><!--#f-navi-->
<div id="footer-bottom" class="clearfix">

<div id="footer-group">[グループサイト] <a href="http://www.serviced-apartments-tokyo.com/">東京サービスアパートメント</a> | <a href="http://www.kujapan.com/">日遊酷棒</a> | <a href="http://www.tokyoapt-rent.com/">Tokyo Apartments Rent</a></div>

<div id="copyright">
<img src="/img/common/copyright.gif" alt="Copyroght (c) HACHIONE Inc. All Right Reserved." width="270" height="30" />
</div><!--#copyright-->
</div><!--#footer-bottom-->
</div><!--#footer-inner-->
</div><!--#footer-->
{include file="include/common/analytics.inc"}