    <div id="g-navi-new">
    <h3><img src="/img/common/news_top.jpg" alt="お知らせ" /></h3>
    <ul>
    <li class="navy"><a href="http://www.youtube.com/watch?v=YTFKhTRmNIs&list=UUezJIH5Fw6BKox_urjUB7Gw&index=1&feature=plcp" target="blank">2012/9/28<br />「やまとごころTV」に弊社が出演しました。</a></li>
    <li class="navy"><a href="http://www.yamatogokoro.jp/inbound-interview/index03.html" target="blank">2012/8/23<br />「やまとごころ.jp」に弊社が掲載されました。</a></li>
    <li class="navy"><a href="http://www.k-tsushin.jp/inbound/search/details/008238/" target="blank">2012/4/13<br />「インバウンド観光支援のプロフェッショナル30」に弊社が掲載されました。</a></li>
    </ul>
    </div>
    